/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alurahotel;

import alurahotel.logica.Editor;
import alurahotel.logica.GuardarRegistro;
import alurahotel.logica.ObtenerReserva;
import alurahotel.logica.PanelesPersonalizados;
import alurahotel.logica.Salida;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * @author bjimenez
 */
public class Registro extends javax.swing.JFrame {

     private Editor editor;
     private Salida salida;
     private ObtenerReserva obtenerReserva;
     private GuardarRegistro guardarRegistro = new GuardarRegistro();
     
     
    public Registro(){
        initComponents();
        this.setLocationRelativeTo(null); 
       
        obtenerReserva = new ObtenerReserva();
        obtenerReserva.Setearnumero(numReserva);
      
        salida = new Salida();
        editor = new Editor();
        
        editor.ajustarImagen(fondo, "src\\alurahotel\\imagenes\\Menu.jpg");
        editor.ajustarImagen(salir, "src\\alurahotel\\imagenes\\salida.png");
        editor.ajustarImagen(regresa, "src\\alurahotel\\imagenes\\atras.png");
        editor.ajustarImagen(titular, "src\\alurahotel\\imagenes\\turista.png");
        editor.ajustarImagen(guardar, "src\\alurahotel\\imagenes\\guardar.png");
        editor.ajustarImagen(cancelar, "src\\alurahotel\\imagenes\\cancelar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        regresa = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        guardar = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        numReserva = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, 40));

        salirBtn.setBackground(new java.awt.Color(250, 250, 250));
        salirBtn.setBorder(null);
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel2.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, 40));

        regresa.setBackground(new java.awt.Color(250, 250, 250));
        regresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresaMouseClicked(evt);
            }
        });
        jPanel2.add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 40));

        titular.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.add(titular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 70));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Huésped");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel2.setText("Número de Reserva");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        jLabel3.setBackground(new java.awt.Color(250, 250, 250));
        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, -1));

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel4.setText("Nombres");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        id.setBackground(new java.awt.Color(153, 153, 153));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        id.setCaretColor(new java.awt.Color(51, 51, 51));
        id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 20));

        apellido.setBackground(new java.awt.Color(153, 153, 153));
        apellido.setForeground(new java.awt.Color(255, 255, 255));
        apellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        apellido.setCaretColor(new java.awt.Color(51, 51, 51));
        apellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        jPanel2.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 130, 20));

        telefono.setBackground(new java.awt.Color(153, 153, 153));
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        telefono.setCaretColor(new java.awt.Color(51, 51, 51));
        telefono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel2.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, 20));

        nombre.setBackground(new java.awt.Color(153, 153, 153));
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombre.setCaretColor(new java.awt.Color(51, 51, 51));
        nombre.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, 20));

        jLabel5.setBackground(new java.awt.Color(250, 250, 250));
        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 120, -1));

        jLabel6.setBackground(new java.awt.Color(250, 250, 250));
        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 211, 120, 20));

        jLabel7.setBackground(new java.awt.Color(250, 250, 250));
        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel7.setText("Identificacion (ID)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, -1));

        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        jPanel2.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 50, 40));

        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });
        jPanel2.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 40, 40));

        fechaNacimiento.setBackground(new java.awt.Color(153, 153, 153));
        fechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 130, 30));

        numReserva.setBackground(new java.awt.Color(255, 255, 255));
        numReserva.setForeground(new java.awt.Color(51, 51, 51));
        numReserva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(numReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 580, 330));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        salida.Mensaje(this);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char valido = evt.getKeyChar();
        if(Character.isDigit(valido)){
            getToolkit().beep();
            evt.consume();
            List<String> botones = Arrays.asList("Entendido");
                PanelesPersonalizados optionPane = new PanelesPersonalizados(
                    "Por favor, solo ingrese letras.",
                    "Tipo de dato incompatible",
                botones,
                  "/alurahotel/imagenes/incompatible.png",
                 60,
                 60
                );
                optionPane.Mostrar();
        }
            
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped
        char valido = evt.getKeyChar();
        if(Character.isDigit(valido)){
            getToolkit().beep();
            evt.consume();
            List<String> botones = Arrays.asList("Entendido");
                PanelesPersonalizados optionPane = new PanelesPersonalizados(
                    "Por favor, solo ingrese letras.",
                    "Tipo de dato incompatible",
                botones,
                  "/alurahotel/imagenes/incompatible.png",
                 60,
                 60
                );
                optionPane.Mostrar();
        }
    }//GEN-LAST:event_apellidoKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
         char valido = evt.getKeyChar();
       if(Character.isLetter(valido)){
           getToolkit().beep();
           evt.consume();
            List<String> botones = Arrays.asList("Entendido");
                PanelesPersonalizados optionPane = new PanelesPersonalizados(
                    "Por favor, solo ingrese números.",
                    "Tipo de dato incompatible",
                botones,
                  "/alurahotel/imagenes/incompatible.png",
                 60,
                 60
                );
                optionPane.Mostrar();
       }
    }//GEN-LAST:event_telefonoKeyTyped

    private void regresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresaMouseClicked
        Reserva reserva = new Reserva();
        reserva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresaMouseClicked

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
       
        String numeroId = id.getText();
        
        String getNombre = nombre.getText();
        String getApellido = apellido.getText();
        Date getFecha = fechaNacimiento.getDate();
        String getTelefono = telefono.getText();
        
        String getReserva = numReserva.getText();
        int reserva = Integer.parseInt(getReserva);
        
        guardarRegistro.guardarRegistro(numeroId, getNombre, getApellido, getFecha,
                getTelefono, reserva, this, nombre, apellido,
                apellido, numReserva, telefono, fechaNacimiento);
        
    }//GEN-LAST:event_guardarMouseClicked

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
       char valido = evt.getKeyChar();
       if(Character.isLetter(valido)){
           getToolkit().beep();
           evt.consume();
            List<String> botones = Arrays.asList("Entendido");
                PanelesPersonalizados optionPane = new PanelesPersonalizados(
                    "Por favor, solo ingrese números.",
                    "Tipo de dato incompatible",
                botones,
                  "/alurahotel/imagenes/incompatible.png",
                 60,
                 60
                );
                optionPane.Mostrar();
                
       }
    }//GEN-LAST:event_idKeyTyped

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
       List<String> botones = Arrays.asList("Si", "No");
                PanelesPersonalizados optionPane = new PanelesPersonalizados(
                    "Estas seguro que deseas cancelar el registro del huesped?",
                    "Cancelacion de Registro",
                botones,
                  "/alurahotel/imagenes/confundido.png",
                 60,
                 60
                );
                int resultado = optionPane.Mostrar();
                if(resultado == 0){
                    this.setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                
                }
    }//GEN-LAST:event_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JLabel cancelar;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel guardar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel numReserva;
    private javax.swing.JLabel regresa;
    private javax.swing.JLabel salir;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel titular;
    // End of variables declaration//GEN-END:variables


}
