/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alurahotel;

import alurahotel.logica.Conexion;
import alurahotel.logica.Editor;
import alurahotel.logica.GenerarNumero;
import alurahotel.logica.GuardarReserva;
import alurahotel.logica.PrecioReserva;
import alurahotel.logica.RegistroComboBox;
import alurahotel.logica.Salida;
import java.beans.PropertyChangeListener;
import java.util.Date;

/**
 *
 * @author bjimenez
 */
public class Reserva extends javax.swing.JFrame {
     private Conexion conexion = new Conexion();
     private Salida salida;
     private Editor editor;
     private RegistroComboBox combo; 
     private PrecioReserva precioReserva = new PrecioReserva();
     private GuardarReserva guardarReserva = new GuardarReserva();
     private GenerarNumero generarNumero = new GenerarNumero();

    public Reserva() {
        initComponents();
        this.setLocationRelativeTo(null);
        conexion.estableceConexion();
        
       
        
        combo = new RegistroComboBox();
        
        combo.cargarComboHabitacion(habitacion);
        combo.cargarComboFormaPago(formaPago);
      
        salida = new Salida();
        editor = new Editor();
        
        editor.ajustarImagen(fondo, "src\\alurahotel\\imagenes\\Menu.jpg");
        editor.ajustarImagen(salir, "src\\alurahotel\\imagenes\\salida.png");
        editor.ajustarImagen(regresa, "src\\alurahotel\\imagenes\\atras.png");
        editor.ajustarImagen(titular, "src\\alurahotel\\imagenes\\reserva.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        regresa = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registro = new javax.swing.JButton();
        fechaCheckOut = new com.toedter.calendar.JDateChooser();
        fechaCheckIn = new com.toedter.calendar.JDateChooser();
        habitacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        formaPago = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, 40));

        salirBtn.setBackground(new java.awt.Color(250, 250, 250));
        salirBtn.setBorder(null);
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel2.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, 40));

        regresa.setBackground(new java.awt.Color(250, 250, 250));
        regresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresaMouseClicked(evt);
            }
        });
        jPanel2.add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 40));

        titular.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.add(titular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 70));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reserva");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel2.setText("Fecha del Check-Out");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, -1));

        jLabel3.setBackground(new java.awt.Color(250, 250, 250));
        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel3.setText("Tipo de Habitación");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, -1));

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel4.setText("Fecha del Check-In");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, -1));

        registro.setBackground(new java.awt.Color(255, 106, 24));
        registro.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        registro.setForeground(new java.awt.Color(255, 255, 255));
        registro.setText("CONTINUAR");
        registro.setBorder(null);
        registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel2.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 30));

        fechaCheckOut.setBackground(new java.awt.Color(153, 153, 153));
        fechaCheckOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fechaCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        fechaCheckOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaCheckOutPropertyChange(evt);
            }
        });
        jPanel2.add(fechaCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 30));

        fechaCheckIn.setBackground(new java.awt.Color(153, 153, 153));
        fechaCheckIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fechaCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        fechaCheckIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaCheckInPropertyChange(evt);
            }
        });
        jPanel2.add(fechaCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 30));

        habitacion.setBackground(new java.awt.Color(153, 153, 153));
        habitacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        habitacion.setForeground(new java.awt.Color(255, 255, 255));
        habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionActionPerformed(evt);
            }
        });
        jPanel2.add(habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, 30));

        jLabel5.setBackground(new java.awt.Color(250, 250, 250));
        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel5.setText("Total a pagar");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 120, -1));

        formaPago.setBackground(new java.awt.Color(153, 153, 153));
        formaPago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        formaPago.setForeground(new java.awt.Color(255, 255, 255));
        formaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaPagoActionPerformed(evt);
            }
        });
        jPanel2.add(formaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 140, 30));

        jLabel6.setBackground(new java.awt.Color(250, 250, 250));
        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel6.setText("Método de Pago");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 120, -1));

        precioTotal.setBackground(new java.awt.Color(255, 255, 255));
        precioTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(51, 51, 51));
        precioTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 580, 330));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        salida.Mensaje(this);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        
        
        
        Date checkIn = fechaCheckIn.getDate();
        Date checkOut = fechaCheckOut.getDate();
        String tipoHabitacion = (String) habitacion.getSelectedItem();
        String comoPagar = (String) formaPago.getSelectedItem();
        double pago = costoTotal;
        int numReserva = generarNumero.generateRandomNumber();
        
        guardarReserva.Guardar(checkIn, checkOut, tipoHabitacion, comoPagar, pago,
                numReserva, fechaCheckIn, fechaCheckOut);
        
       this.setVisible(false);
        
    }//GEN-LAST:event_registroActionPerformed

    private void formaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formaPagoActionPerformed

    private void habitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionActionPerformed
       habitacion.addActionListener(e -> dateChangeListener.propertyChange(null));
    }//GEN-LAST:event_habitacionActionPerformed

    private void regresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresaMouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresaMouseClicked

    private void fechaCheckInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaCheckInPropertyChange
        fechaCheckIn.addPropertyChangeListener(dateChangeListener);
    }//GEN-LAST:event_fechaCheckInPropertyChange

    private void fechaCheckOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaCheckOutPropertyChange
        fechaCheckOut.addPropertyChangeListener(dateChangeListener);
    }//GEN-LAST:event_fechaCheckOutPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaCheckIn;
    private com.toedter.calendar.JDateChooser fechaCheckOut;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> formaPago;
    private javax.swing.JComboBox<String> habitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JButton registro;
    private javax.swing.JLabel regresa;
    private javax.swing.JLabel salir;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel titular;
    // End of variables declaration//GEN-END:variables
    double costoTotal;
    PropertyChangeListener dateChangeListener  = evt -> {
            Date checkIn = fechaCheckIn.getDate();
            Date checkOut = fechaCheckOut.getDate();
            String seleccion = (String) habitacion.getSelectedItem();
            
            if(checkIn != null && checkOut != null){

                costoTotal = precioReserva.calcularCosto(checkIn, checkOut, seleccion);
                precioTotal.setText(costoTotal + "$ dólares");
            } 
    };
}
